name: Automated Penguin Prediction

on:
  schedule:
    - cron: '30 7 * * *'  # Runs daily at 07:30 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Prediction Script
      run: python scripts/prediction.py

    - name: Commit and Push Updated Predictions
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add docs/latest_prediction.json docs/prediction_history.json docs/index.html
        git commit -m "Updated prediction data"
        git push origin main
